### ISSUE TITLE
Difference in error handling between launching world through setup screen and through --world argument

### ISSUE THREAD

**Issue by rikmarais** [foundryvtt/foundryvtt#10016]
### What happened?

There appears to be a difference in error handling between launching world through setup screen and through --world argument

One example of where this surfaces is if an empty string `name: ""` user exists in the users database
With many users coming from v10, where it was easier to edit users.db, sometimes we come across empty string named users in the database.
When using --world=id to run the world as a default world, the process crashes and the Foundry logs do not log the reason for the error.

The second example of where this surfaces is any failure to launch the world, such as in https://github.com/foundryvtt/foundryvtt/issues/9979. Any failure to launch a world when using the --world=id that would normally just return you to the Foundry setup screen will crash the process and emit the error outside of logging, which makes these cases very challenging to troubleshoot.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

**Note:** Two error cases reported here.

**First error case**: `name: ""` user in `users` database
[pf2e-break-test.zip](https://github.com/foundryvtt/foundryvtt/files/12655018/pf2e-break-test.zip) contains such a `users` database.
- Run Foundry `node main.js` and attempt to launch the world through setup screen. World launches and can be joined.
- Attempt to launch directly into the world with `node main.js --world=pf2e-break-test`. Process crashes with a TypeError

![image](https://github.com/foundryvtt/foundryvtt/assets/34374883/d4ee111c-5d20-4e6f-b30f-7c7346ee26b3)

---
**Second error case**: Any instance of World Launch Failed
- Using a world that would cause https://github.com/foundryvtt/foundryvtt/issues/9979 or any other World Launch Failed 
- (Optionally: prior to v11.308 you can also use any world with a corrupted leveldb world database)
- Launch world through setup screen with `node main.js`. Receive World Launch Failed notification, and world does not open.

![image](https://github.com/foundryvtt/foundryvtt/assets/34374883/1373850d-7201-465f-a411-f383d59e1aba)

- Attempt to launch directly into the world with `node main.js --world=id`. The process crashes and does not log an error to the Foundry logs. 

The below screenshot shows logs from `node main.js` and using the setup screen to open the world (left) and `node main.js --world=id` and opening the world as the default world (right)

![image](https://github.com/foundryvtt/foundryvtt/assets/34374883/1e35134f-9728-4d67-9c02-3f37c962e4fe)

### What core version are you reporting this for?

Version 11.308

### Relevant log output

```shell
First error case: `name: ""` user in `users` database
---
C:\Users\Phi\FoundryVTT-11.308\resources\app>node main.js --world=pf2e-break-test
FoundryVTT | 2023-09-19 04:18:00 | [info] Running on Node.js - Version 18.14.0
FoundryVTT | 2023-09-19 04:18:00 | [info] Foundry Virtual Tabletop - Version 11 Build 308
FoundryVTT | 2023-09-19 04:18:00 | [info] User Data Directory - "C:/Users/Phi/AppData/Local/FoundryVTT"
FoundryVTT | 2023-09-19 04:18:00 | [info] Application Options:
{
  "compressStatic": true,
  "fullscreen": false,
  "hostname": null,
  "language": "en.core",
  "localHostname": null,
  "port": 30000,
  "protocol": null,
  "proxyPort": null,
  "proxySSL": false,
  "routePrefix": null,
  "updateChannel": "stable",
  "upnp": true,
  "upnpLeaseDuration": null,
  "awsConfig": null,
  "passwordSalt": null,
  "sslCert": null,
  "sslKey": null,
  "world": null,
  "serviceConfig": null,
  "telemetry": false,
  "compressSocket": true,
  "cssTheme": "foundry",
  "hotReload": false,
  "deleteNEDB": false,
  "adminPassword": "••••••••••••••••"
}
FoundryVTT | 2023-09-19 04:18:00 | [info] Software license verification succeeded
FoundryVTT | 2023-09-19 04:18:00 | [info] Requesting UPnP port forwarding to destination port 30000
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "actors"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "cards"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "messages"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "combats"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "drawings"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "fog"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "folders"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "items"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "journal"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "macros"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "playlists"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "tables"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "scenes"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "settings"
FoundryVTT | 2023-09-19 04:18:01 | [info] FoundryVTT | Connected to database "users"
FoundryVTT | 2023-09-19 04:18:01 | [warn] User [ncQs4yUwPUSnMpbp] validation errors:
  name: may not be undefined
Error: User [ncQs4yUwPUSnMpbp] validation errors:
  name: may not be undefined
    at DataModelValidationFailure.asError (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/data/validation-failure.mjs:81:12)
    at User.validate (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/abstract/data.mjs:309:34)
    at new DataModel (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/abstract/data.mjs:62:10)
    at new Document (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/abstract/document.mjs:17:16)
    at new BaseUser (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/documents/user.mjs:35:1)
    at new ServerDocumentMixin (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/database/backend/server-document.mjs:1:507)
    at new User (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/database/documents/user.mjs:1:280)
    at User.fromSource (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/abstract/data.mjs:542:12)
    at User.fromSource (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/database/documents/user.mjs:1:2030)
    at map (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/database/backend/server-document.mjs:1:5199)
file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/database/documents/user.mjs:1
import ServerDocumentMixin from"../backend/server-document.mjs";import BaseUser from"../../../common/documents/user.mjs";import sessions from"../../sessions.mjs";import{createPassword}from"../../core/auth.mjs";import{USER_ROLES}from"../../../common/constants.mjs";export default class User extends(ServerDocumentMixin(BaseUser)){get sessions(){return sessions.getUserSessions(this.id)}get sockets(){const e=[];for(let s of config.sockets.values())s.userId===this.id&&e.push(s);return e}get isActive(){return!!this.id&&(game.active&&game.activity&&this.id in game.activity.users)}async _preCreate(e,s,t){await this.#e();const{hash:r,salt:o}=createPassword(this.password);this.updateSource({password:r,passwordSalt:o})}_onCreate(e,s,t){game.users.push(this)}async _preUpdate(e,s,t){if(await this.#e(),"password"in e){const{hash:s,salt:t}=createPassword(e.password);this.updateSource({password:s,passwordSalt:t}),sessions.deactivateUserSession(this.id)}if("role"in e&&(this.role>t.role||e.role>t.role))throw new Error("You are not authorized to perform this role change.");const r=CONST.USER_ROLES.GAMEMASTER;if("role"in e&&e.role<r&&this.role===r&&!game.users.find((e=>e.role===r&&e.id!==this.id)))throw new Error("You may not demote the only Gamemaster user within the World.")}_onUpdate(e,s,t){db.User.get(this.id).then((e=>game.users.findSplice((e=>e.id===this.id),e))),delete e.password,delete e.passwordSalt}async _preDelete(e,s){const t=CONST.USER_ROLES.GAMEMASTER;if(this.role===t&&!game.users.find((e=>e.role===t&&e.id!==this.id)))throw new Error("You may not delete the only Gamemaster user within the World.")}_onDelete(e,s){game.users.findSplice((e=>e.id===this.id))}async#e(){if((await User.find({name:this.name})).find((e=>e.id!==this.id)))throw new Error(`User names must be unique, the name ${this.name} is already taken`)}static async dump(e={}){const s=await super.dump(e);return s.forEach((e=>{delete e.password,delete e.passwordSalt})),s.sort(this._sort),s}static fromSource(e,{safe:s=!1,...t}={}){const r=super.fromSource(e,t);return s&&r.updateSource({password:"",passwordSalt:""}),r}static async find(e={},s={}){const t=await super.find(e,s);return t.sort(this._sort),t}static async getUsers(){const e=await User.find({}),s=game.activity.users;for(let t of e){if(!t.id)continue;const e=s[t.id]||{};t.viewedScene=e.sceneId||null}return game.users=e}static _sort(e,s){let t=e.role>=USER_ROLES.ASSISTANT?e.role:1,r=s.role>=USER_ROLES.ASSISTANT?s.role:1;return t!==r?r-t:e.name.localeCompare(s.name)}}





TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at _sort (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/database/documents/user.mjs:1:2495)
    at Array.sort (<anonymous>)
    at User.find (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/database/documents/user.mjs:1:2172)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async User.getUsers (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/database/documents/user.mjs:1:2223)
    at async World.setup (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/packages/world.mjs:1:8517)
    at async Module.initialize (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/init.mjs:1:1967)

Node.js v18.14.0

---
Second error case: Any instance of World Launch Failed when using --world=id
---
FoundryVTT | 2023-09-19 03:37:39 | [info] FoundryVTT | Connected to database "pf2e.kingmaker-features"
FoundryVTT | 2023-09-19 03:37:39 | [info] Migrating World outlaws-of-alkenstar to upgraded pf2e System version 5.4.4
FoundryVTT | 2023-09-19 03:37:39 | [info] FoundryVTT | Migrating Actor documents to the latest game system data model
FoundryVTT | 2023-09-19 03:37:39 | [info] FoundryVTT | Created 0 Folder documents with ids: []
FoundryVTT | 2023-09-19 03:37:41 | [info] Successfully migrated 398 Actor documents to the latest system data model.
FoundryVTT | 2023-09-19 03:37:41 | [info] FoundryVTT | Migrating Cards documents to the latest game system data model
FoundryVTT | 2023-09-19 03:37:41 | [info] Successfully migrated 0 Cards documents to the latest system data model.
FoundryVTT | 2023-09-19 03:37:41 | [info] FoundryVTT | Migrating Item documents to the latest game system data model
FoundryVTT | 2023-09-19 03:37:41 | [info] Successfully migrated 4 Item documents to the latest system data model.
FoundryVTT | 2023-09-19 03:37:41 | [info] FoundryVTT | Migrating Scene documents to the latest game system data model
file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/data/validation-failure.mjs:81
    return new DataModelValidationError(this);
           ^

DataModelValidationError: Actor [SE4VD085yGdB3XD6] validation errors:
  name: may not be undefined
    at DataModelValidationFailure.asError (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/data/validation-failure.mjs:81:12)
    at Actor.validate (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/abstract/data.mjs:308:59)
    at new DataModel (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/abstract/data.mjs:62:10)
    at new Document (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/abstract/document.mjs:17:16)
    at new BaseActor (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/documents/actor.mjs:36:1)
    at new ServerDocumentMixin (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/database/backend/server-document.mjs:1:507)
    at new Actor (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/database/documents/actor.mjs:1:381)
    at ActorDelta.applyDelta (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/common/documents/actor-delta.mjs:116:12)
    at Token.loadRelatedDocuments (file:///C:/Users/Phi/FoundryVTT-11.308/resources/app/dist/database/documents/token.mjs:1:538)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.14.0

C:\Users\Phi\FoundryVTT-11.308\resources\app>
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by rikmarais** [comment]
Thanks a bunch for looking into this!

The first error case, where `name: ""` user exists in the users database can be replicated with this [pf2e-break-test.zip](https://github.com/foundryvtt/foundryvtt/files/12655018/pf2e-break-test.zip) world. In the very rare cases where I've encountered this in the wild, it's usually due to a manually packaged `users` db file, so I replicated that with this zip.

The second error case is much harder to create on purpose, but theoretically any world that fails to open because of https://github.com/foundryvtt/foundryvtt/issues/9979 can be used to replicate this behaviour. I'll reach out on Discord to provide a test world 👍
