### ISSUE TITLE
Invalid Token tint can cause a Scene to fail loading

### ISSUE THREAD

**Issue by TheMathKing** [foundryvtt/foundryvtt#10302]
### What happened?

I had attempted to place a token into a scene when the resolution was weird (I was loading tokens into foundry and had it split on my main monitor). What this did, effectively, was to lock out access to that scene. When I log into a player account, for some reason, the scene appears on both client and server and with it the visuals of the issue: The token that was added to the scene before has it's image in the far top-left corner of the scene (well beyond the grid), while it's token outline is in the middle of the map, where it was placed. This "token" cannot be deleted or moved. 

Details:
-The server is the up-to-date application in windows
-the client I used for the player is on chrome
-I have the latest version (V11.315)
-I have many mods...
-attempting to move this strange token only results in it being "pingged"

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

I corrupted a similar scene like this as well.

### What core version are you reporting this for?

(V11.315)

### Relevant log output

```shell
When this token is being moved.

commons.js:2070 Error: You are accessing the SwpActor#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:2059:19)
    at SwpActor._logV10CompatibilityWarning (commons.js:8544:14)
    at get data [as data] (commons.js:8432:24)
    at getProperty (commons.js:2539:41)
    at GenericSpeedProvider.getRanges (speed_provider.js:118:33)
    at getRangesFromSpeedProvider (api.js:90:39)
    at DragRulerRuler.dragRulerGetColorForDistance (ruler.js:461:28)
    at DragRulerRuler._drawMeasuredPath (ruler.js:298:23)
    at DragRulerRuler.performPostPathfindingActions (ruler.js:177:9)
    at DragRulerRuler.measure (ruler.js:134:16)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁CONFIG.Canvas.rulerClass.prototype.measure#toggle-snap-to-grid (toggle-snap-to-grid.js:275:20)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Canvas.rulerClass.prototype.measure#0 (libWrapper-wrapper.js:189:20)
    at DragRulerRuler.update (foundry.js:37644:34)
    at DragRulerRuler.update (ruler.js:76:10)
    at ControlsLayer.updateRuler (foundry.js:36908:16)
    at a._handleUserActivity (foundry.js:17695:23)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at a.handleUserActivity (socketlib.js:320:17)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Users.prototype.constructor._handleUserActivity#0 (libWrapper-wrapper.js:189:20)
    at L.emit (index.mjs:136:20)
    at a.value (socket.js:498:20)
    at a.value (socket.js:485:18)
    at a.value (socket.js:455:22)
    at L.emit (index.mjs:136:20)
    at manager.js:207:18
logCompatibilityWarning @ commons.js:2070
_logV10CompatibilityWarning @ commons.js:8544
get data @ commons.js:8432
getProperty @ commons.js:2539
getRanges @ speed_provider.js:118
getRangesFromSpeedProvider @ api.js:90
dragRulerGetColorForDistance @ ruler.js:461
_drawMeasuredPath @ ruler.js:298
performPostPathfindingActions @ ruler.js:177
measure @ ruler.js:134
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁CONFIG.Canvas.rulerClass.prototype.measure#toggle-snap-to-grid @ toggle-snap-to-grid.js:275
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁CONFIG.Canvas.rulerClass.prototype.measure#0 @ libWrapper-wrapper.js:189
update @ foundry.js:37644
update @ ruler.js:76
updateRuler @ foundry.js:36908
_handleUserActivity @ foundry.js:17695
🎁call_wrapped @ libWrapper-wrapper.js:507
handleUserActivity @ socketlib.js:320
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁Users.prototype.constructor._handleUserActivity#0 @ libWrapper-wrapper.js:189
L.emit @ index.mjs:136
value @ socket.js:498
value @ socket.js:485
value @ socket.js:455
L.emit @ index.mjs:136
(anonymous) @ manager.js:207
Promise.then (async)
it @ websocket-constructor.browser.js:5
value @ manager.js:206
L.emit @ index.mjs:136
value @ index.js:131
value @ manager.js:193
L.emit @ index.mjs:136
value @ socket.js:324
L.emit @ index.mjs:136
value @ transport.js:97
value @ transport.js:89
ws.onmessage @ websocket.js:69
commons.js:2070 Error: You are accessing SwpActor#data which has been migrated to SwpActor#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:2059:19)
    at SwpActor._logDataFieldMigration (commons.js:8533:14)
    at Object.get (commons.js:8497:18)
    at getProperty (commons.js:2539:41)
    at GenericSpeedProvider.getRanges (speed_provider.js:118:33)
    at getRangesFromSpeedProvider (api.js:90:39)
    at DragRulerRuler.dragRulerGetColorForDistance (ruler.js:461:28)
    at DragRulerRuler._drawMeasuredPath (ruler.js:298:23)
    at DragRulerRuler.performPostPathfindingActions (ruler.js:177:9)
    at DragRulerRuler.measure (ruler.js:134:16)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁CONFIG.Canvas.rulerClass.prototype.measure#toggle-snap-to-grid (toggle-snap-to-grid.js:275:20)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Canvas.rulerClass.prototype.measure#0 (libWrapper-wrapper.js:189:20)
    at DragRulerRuler.update (foundry.js:37644:34)
    at DragRulerRuler.update (ruler.js:76:10)
    at ControlsLayer.updateRuler (foundry.js:36908:16)
    at a._handleUserActivity (foundry.js:17695:23)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at a.handleUserActivity (socketlib.js:320:17)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Users.prototype.constructor._handleUserActivity#0 (libWrapper-wrapper.js:189:20)
    at L.emit (index.mjs:136:20)
    at a.value (socket.js:498:20)
    at a.value (socket.js:485:18)
    at a.value (socket.js:455:22)
    at L.emit (index.mjs:136:20)
    at manager.js:207:18
logCompatibilityWarning @ commons.js:2070
_logDataFieldMigration @ commons.js:8533
get @ commons.js:8497
getProperty @ commons.js:2539
getRanges @ speed_provider.js:118
getRangesFromSpeedProvider @ api.js:90
dragRulerGetColorForDistance @ ruler.js:461
_drawMeasuredPath @ ruler.js:298
performPostPathfindingActions @ ruler.js:177
measure @ ruler.js:134
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁CONFIG.Canvas.rulerClass.prototype.measure#toggle-snap-to-grid @ toggle-snap-to-grid.js:275
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁CONFIG.Canvas.rulerClass.prototype.measure#0 @ libWrapper-wrapper.js:189
update @ foundry.js:37644
update @ ruler.js:76
updateRuler @ foundry.js:36908
_handleUserActivity @ foundry.js:17695
🎁call_wrapped @ libWrapper-wrapper.js:507
handleUserActivity @ socketlib.js:320
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁Users.prototype.constructor._handleUserActivity#0 @ libWrapper-wrapper.js:189
L.emit @ index.mjs:136
value @ socket.js:498
value @ socket.js:485
value @ socket.js:455
L.emit @ index.mjs:136
(anonymous) @ manager.js:207
Promise.then (async)
it @ websocket-constructor.browser.js:5
value @ manager.js:206
L.emit @ index.mjs:136
value @ index.js:131
value @ manager.js:193
L.emit @ index.mjs:136
value @ socket.js:324
L.emit @ index.mjs:136
value @ transport.js:97
value @ transport.js:89
ws.onmessage @ websocket.js:69
```

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by TheMathKing** [comment]
I have found the cause of this error. The "scene destroying" tokens are ones where I put their "tint" in via an invalid RGB text code. For example, for the proper code "#e3c2d9" (a pink), I put "#e5bcddc8", which is the same color in another format, into the "Tint Color" field. This produced a scene-destroying token!

**Comment by aaclayton** [comment]
This may already be fixed by our work in V12 to improve usage of the `Color` class and various color fields, but if not we'll get it fixed.

**Comment by aaclayton** [comment]
@dev7355608 could you look into this one and see if it's still an issue in V12?
