### ISSUE TITLE
Playlists Tab Does Not Render elements

### ISSUE THREAD

**Issue by JaysonMendoza** [foundryvtt/foundryvtt#10312]
### What happened?

Playlist Tab unable to render elements. It appears as a blank tab when it should contain a number of playlists. No controls for folder or  playlist management render. If you right click on the tab an error will appear in the console. 

Possible Cause:
Using developer tools it seems to be a recursion error as part of the algorithm and likely hit the language limit for the call stack. This is likely caused by the combined playlists including too many entries for the algorithm used. The only safe solution is likely to convert the recursive call to a loop since we cannot know that any combination of playlists will never exceed a finite stack size. 
![image](https://github.com/foundryvtt/foundryvtt/assets/43111928/64a1a083-a1da-43c3-92b2-d4c6351602e5)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

1. Keep adding modules that include sound's in compendium
2. Import them into playlists
3. Eventually a limit will be reached the program tab cannot render. You also cannot seem to fix it.

### What core version are you reporting this for?

Version 11 Stable, 315

### Relevant log output

```shell
On Right Click:
foundry.js:753  RangeError: An error occurred while rendering PlaylistDirectory 158. Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at S.fn.init (jquery.min.js:2:25611)
    at S (jquery.min.js:2:1051)
    at PlaylistDirectory._renderInner (foundry.js:5975:12)
    at async PlaylistDirectory._renderInner (foundry.js:69038:16)
    at async PlaylistDirectory._render (foundry.js:5818:19)
    at async PlaylistDirectory._render (foundry.js:69030:5)
onError @ foundry.js:753
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:5771
Promise.catch (async)
render @ foundry.js:5769
renderPopout @ foundry.js:69087
_onRightClickTab @ foundry.js:70995
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by JaysonMendoza** [comment]
Please let me know if you need any files to check the state on server side. I also manage the server.

**Comment by aaclayton** [comment]
Hi @JaysonMendoza could you please confirm that you encounter the same issue with modules disabled? The error message call stack here suggests there may be some module interactions in play. 

I understand from your original report that modules were involved as the source from which playlists were imported in the first place, but does the sidebar still fail to render if you have all modules disabled? Could you paste the contents of the **Support Report** from the Settings tab?

**Comment by JaysonMendoza** [comment]
As a response to your question, I reported this bug after I reloaded the world in safe mode with all the modules disabled. 

Now an oddity. After doing that I reloaded all the modules again and had the bug once more. Then I left for a couple of hours since my ticket was posted and now it's working again.

I investigated the server logs and couldn't find anything of value either.

It would make sense that it was a module and that is what I initially suspected. What made me report the bug was that it occurred when I disabled all modules in safe mode. 

Was there perhaps a cache somewhere on client side or server side that might have been corrupted? The only thing I can think of that could cause this behavior are that the front-end code was reading from a cache left on the client that might have been deleted since. That could have allowed the bug to persist after resets.

Alternatively, it could be some routine on server side that might have detected some corruption in the cache and then regenerated the file. Though I would assume that should be logged if it was done.

Is there a debug level that can be set somewhere so it loggs what module routine was being executed during a crash?
