### ISSUE TITLE
Importing an adventure can throw an error in some cases

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10853]
Originally reported by patrikp https://discord.com/channels/170995199584108546/1184176415139184731/1237106284189188256

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: Windows, NodeJS (v20), Chrome
**Short Description of bug**: Error when importing v10 Adventure 
**Simple steps to reproduce the bug**: Start with an empty world. Import an adventure created in v10 (did not test with adventure created in later versions.)

EDIT: Can be reproduced in v12 only by creating an adventure, adding an actor to the adventure, build the adventure, import the adventure.

**Screenshots and/or console errors**:
```foundry.js:6675 TypeError: Cannot read properties of undefined (reading 'render')
    at Folders.render (foundry.js:13268:18)
    at Folders._onModifyContents (foundry.js:11937:12)
    at #handleUpdateDocuments (foundry-esm.js:43936:18)
    at async Folder.updateDocuments (foundry-esm.js:9467:23)
    at async Adventure.importContent (foundry.js:15734:20)
    at async Adventure.import (foundry.js:15652:32)
    at async AdventureImporter._onSubmit (foundry.js:6672:7)```

Seems like it works when changing from ```collection.render``` to ```collection?.render``` in Folders.render() :

```  render(force, options={}) {
    const documents = options.renderData || [];
    if ( documents.length ) {
      const sample = documents[0];
      if ( sample.type === "Compendium" ) return ui.sidebar.tabs.compendium.render(force);
      const collection = game.collections.get(sample.type);
      collection.render(force, context);
      if ( sample.type === "JournalEntry" ) {
        this._refreshJournalEntrySheets();
      }
    }
  }```

**Comment by Fyorl** [comment]
Looks like this was an error with folder collection re-rendering which was resolved with #10516
