### ISSUE TITLE
Changing canvas layers with the Light Configuration dialog open throws an error and "unlocks" other light sources

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#10961]
### What happened?

Originally reported by Matt and I just reproduced:

If I open a light config, change to a different tool layer, and then come back, I can move other light sources around which I shouldn't be able to do. Updating the light via the config does still seem to work but it throws this error:

```Uncaught (in promise) TypeError: Cannot read properties of null (reading 'draw')
    at AmbientLightConfig._preRender (foundry-esm.js:48968:35)
    at async #doEvent (foundry-esm.js:44638:20)
    at async #render (foundry-esm.js:44054:7)
    at async Semaphore._try (foundry-esm.js:6630:19)```

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Place at least two lights
2. Open the configuration dialog for one of them
3. Activate a different canvas layer (such as Walls), then reactivate the Light layer
4. Drag the light that is not being edited around in the canvas

Dragging the other light should not be possible, and the error is also present in the console.

### What core version are you reporting this for?

12.323

### Relevant log output

_No response_

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Norc** [comment]
looks like a duplicate of #11076, which was fixed. Confirmed I can no longer reproduce in 12.325.
