### ISSUE TITLE
Changing `globalPlaylistVolume` / `globalAmbientVolume` / `globalInterfaceVolume` does not update the volume sliders in the sidebar tab 

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11061]
```js
game.settings.set("core", "globalPlaylistVolume", Math.random())
// slider is not reflecting the new value
```

**Comment by aaclayton** [comment]
Report from @Syrious

### What happened?

When trying to change volume via code like this

```
Hooks.once("ready", () => {
  game.settings.set("core", "globalPlaylistVolume", 0.0)
  game.settings.set("core", "globalAmbientVolume", 0.0)
  game.settings.set("core", "globalInterfaceVolume", 0.0)
});
```

a TypeError is thrown (sometimes)


### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

* Create a simple script with this content:

```
Hooks.once("ready", () => {
  game.settings.set("core", "globalPlaylistVolume", 0.0)
  game.settings.set("core", "globalAmbientVolume", 0.0)
  game.settings.set("core", "globalInterfaceVolume", 0.0)
});
```

* Load a world using the module with that script and watch console. 
* If no error occurs, manually change volume sliders
* Reload browser
* Error should now be seen

### What core version are you reporting this for?

12 Build 324

### Relevant log output

```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'gainNode')
    at #onChangeMusicVolume (foundry-esm.js:51948:11)
    at #setClient (foundry.js:3420:41)
    at ClientSettings.set (foundry.js:3363:25)
    at Object.fn (index.js:3:17)
    at #call (foundry.js:608:20)
    at Hooks.callAll (foundry.js:565:17)
    at Game.setupGame (foundry.js:8996:11)
    at async Game._initializeGameView (foundry.js:10306:5)
    at async Game.initialize (foundry.js:8896:5)
```


### Bug Checklist

- [ ] The issue occurs while all Modules are disabled
