### ISSUE TITLE
Cannot install large modules on V12

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/foundryvtt#11268]
### What happened?

Related to this comment, https://github.com/foundryvtt/foundryvtt/issues/11121#issuecomment-2182962177, V12 cannot download large (6.1GB) modules, compared to V11 where the same zip works.
![image](https://github.com/foundryvtt/foundryvtt/assets/32039708/9159a49c-4697-430a-ab32-869b274dc028)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Other

### Reproduction Steps

Attempt to install a large module in the admin screen. You can message me (@vauxs) or JB2A to get a link.

### What core version are you reporting this for?

12

### Relevant log output

```shell
RangeError [ERR_OUT_OF_RANGE]: The value of "start" is out of range. It must be >= 0 && <= 9007199254740991. Received 2_706_905_818_365_165_600
    at ReadStream (node:internal/fs/streams:194:5)
    at new ReadStream (C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\graceful-fs\graceful-fs.js:299:28)
    at Object.createReadStream (C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\graceful-fs\graceful-fs.js:341:12)
    at Object.stream (C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\unzipper\lib\Open\index.js:27:19)
    at unzip (C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\unzipper\lib\Open\unzip.js:19:20)
    at vars.stream (C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\unzipper\lib\Open\directory.js:219:20)
    at vars.buffer (C:\Program Files\Foundry Virtual Tabletop\resources\app\node_modules\unzipper\lib\Open\directory.js:222:38)
    at Files._readEntry (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/files/files.mjs:1:2954)
    at file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/files/files.mjs:1:2888
    at Files.processArchive (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/files/files.mjs:1:2417)
    at async Files.summarizeArchive (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/files/files.mjs:1:2782)
    at async PackageInstaller.install (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/installer.mjs:1:670)
    at async #s (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:9166)
    at async Module.install (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:7894)
    at async file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:3245
_onError @ setup.js:2080
_onProgress @ setup.js:2105
(anonymous) @ setup.js:9112
_onProgress @ setup.js:9112
U.emit @ index.mjs:136
value @ socket.js:538
value @ socket.js:525
value @ socket.js:495
U.emit @ index.mjs:136
(anonymous) @ manager.js:204
Promise.then (async)
ce @ websocket-constructor.browser.js:5
value @ manager.js:203
U.emit @ index.mjs:136
value @ index.js:146
value @ manager.js:190
U.emit @ index.mjs:136
value @ socket.js:341
U.emit @ index.mjs:136
value @ transport.js:98
value @ transport.js:90
ws.onmessage @ websocket.js:68

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    at Setup.installPackage (setup.js:8531:44)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Jules-Bens-Aa** [comment]
This error has already impacted quite a few of our users, so it doesn't seem isolated to our setup, nor the nodeJS version (tested V18 and V20), nor the host as we have now tried from Dropbox, Hetzner and directly from Github with the same results. 
And it is most likely related to the size, since we've tried reducing it and it installed correctly.

**Comment by thre-z** [comment]
Possibly related to #9802 ?
