### ISSUE TITLE
Right-clicking on canvas with left mouse button held down throws unhandled exception

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11299]
### What happened?

I saw red though I expected its absence.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Click and hold left mouse button on the canvas.
2. Click right mouse button

### What core version are you reporting this for?

12.328

### Relevant log output

```shell
foundry.js:25445 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'x')
    at Canvas.ping (foundry.js:25445:48)
    at ControlsLayer._onLongPress (foundry.js:35533:19)
    at #onLongPress (foundry.js:25701:21)
    at MouseInteractionManager.callback (foundry.js:30691:17)
    at #handleLongPress (foundry.js:30927:15)
    at foundry.js:30868:30
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by stwlam** [comment]
Possibly of greater significance than red appearing in the console: a right click doesn't seem to register at all when the left mouse button is held down.
