### ISSUE TITLE
Tracking down an invalid embedded document is difficult

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#11449]
Finding an invalid embedded document is very difficult. It would be helpful if the error report included information about the parent document(s); I'm unsure if it's possible to report the UUID directly?

Example error report in SWADE; yes there are modules involved, but this is about the reporting which is untouched.
```md
foundry-esm.js:5293 Error: SwadeItem [k5GwjOHRFPXv0000] validation errors:
  system: 
    additionalStats: 
      rarity: 
        dtype: may not be undefined
    at DataModelValidationFailure.asError (foundry-esm.js:4710:14)
    at SwadeItem.validate (foundry-esm.js:10416:61)
    at new DataModel (foundry-esm.js:10165:12)
    at new Document (foundry-esm.js:10939:3)
    at new BaseItem (foundry-esm.js:14662:7)
    at new ClientDocumentMixin (foundry.js:10516:7)
    at new Item (foundry.js:19308:1)
    at new SwadeItem (SwadeItem.ts:91:5)
    at EmbeddedCollection.createDocument (foundry-esm.js:5230:14)
    at EmbeddedCollection._initializeDocument (foundry-esm.js:5270:20)
    at EmbeddedCollection.initialize (foundry-esm.js:5254:44)
    at EmbeddedCollectionField.initialize (foundry-esm.js:8857:18)
    at SwadeActor._initialize (foundry-esm.js:10324:29)
    at SwadeActor._initialize (foundry-esm.js:11004:13)
    at SwadeActor._initialize (foundry.js:10550:13)
    at new DataModel (foundry-esm.js:10166:12)
    at new Document (foundry-esm.js:10939:3)
    at new BaseActor (foundry-esm.js:13216:7)
    at new ClientDocumentMixin (foundry.js:10516:7)
    at new Actor (foundry.js:15443:1)
    at new SwadeActor (SwadeActor.ts:114:5)
    at SwadeActor.fromSource (foundry-esm.js:10641:14)
    at Actors._initialize (foundry.js:12066:34)
    at new DocumentCollection (foundry.js:12051:10)
    at new DirectoryCollection (foundry.js:11750:10)
    at new WorldCollection (foundry.js:12367:1)
    at new Actors (foundry.js:12553:1)
    at Game.initializeDocuments (foundry.js:9082:30)
    at Game.setupGame (foundry.js:8976:10)
    at async Game._initializeGameView (foundry.js:10354:5)
_handleInvalidDocument @ foundry-esm.js:5293
_initializeDocument @ foundry-esm.js:5273
initialize @ foundry-esm.js:5254
initialize @ foundry-esm.js:8857
_initialize @ foundry-esm.js:10324
_initialize @ foundry-esm.js:11004
_initialize @ foundry.js:10550
DataModel @ foundry-esm.js:10166
Document @ foundry-esm.js:10939
BaseActor @ foundry-esm.js:13216
ClientDocumentMixin @ foundry.js:10516
Actor @ foundry.js:15443
SwadeActor @ SwadeActor.ts:114
fromSource @ foundry-esm.js:10641
_initialize @ foundry.js:12066
DocumentCollection @ foundry.js:12051
DirectoryCollection @ foundry.js:11750
WorldCollection @ foundry.js:12367
Actors @ foundry.js:12553
initializeDocuments @ foundry.js:9082
setupGame @ foundry.js:8976
await in setupGame (async)
_initializeGameView @ foundry.js:10354
_initializeView @ foundry.js:10330
initialize @ foundry.js:8917
await in initialize (async)
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁libWrapperInit @ libWrapper-api.js:805
await in 🎁libWrapperInit (async)
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:187
window.addEventListener.once @ foundry.js:95728
```

**Comment by krbz999** [comment]
Agree with this. It's often difficult to figure out whether an invalid item is in the item directory, on an actor, or on a synthetic actor. Especially so when the troubleshooter does not have access to the world directly but has to guide a (novice) user. Just including the uuid would go a long way.

**Comment by aaclayton** [comment]
I've implemented a more informative error here which provides the UUID of the invalid document: 

![image](https://github.com/user-attachments/assets/3ba1ae2f-e853-4bd3-8fb5-067c68ecba8a)
