### ISSUE TITLE
A dollar sign inside the data of a Roll causes a syntax error

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11440]
```js
CONFIG.Dice.functions.foo = a => a.x;

new Roll("foo(@test)", {test: {x: 1, y: "$"}});

// or

new Roll("foo(@test)", {test: {x: 1, $y: 2}});
```

```
foundry-esm.js:65625 Uncaught SyntaxError: Expected ")", ",", "[", [%*/], [+\-], or whitespace but "\"" found. (at foundry-esm.js:64274:22)
    at new peg$SyntaxError (foundry-esm.js:64274:22)
    at peg$buildStructuredError (foundry-esm.js:64649:14)
    at Object.peg$parse [as parse] (foundry-esm.js:65625:13)
    at Roll.parse (foundry-esm.js:63850:45)
    at new Roll (foundry-esm.js:63197:37)
    at <anonymous>:2:11
```

**Comment by aaclayton** [comment]
@Fyorl do you think we should *intend* to "fix" this, or close as `wontfix`?

**Comment by Fyorl** [comment]
Passing full objects as roll data was not previously supported, it was a new feature we added (with this known limitation), so I don't think it can be considered a bug. But I think we can probably pick a better sigil, something in the unicode space that is much more unlikely to appear in a string or property name.

**Comment by aaclayton** [comment]
> Passing full objects as roll data was not previously supported, it was a new feature we added (with this known limitation), so I don't think it can be considered a bug. But I think we can probably pick a better sigil, something in the unicode space that is much more unlikely to appear in a string or property name.

Let's prioritize the path of swapping to a different character that is rare and thus unlikely to collide.
