### ISSUE TITLE
JournalEntry doesn't support page sheets based on DocumentSheetV2

### ISSUE THREAD

**Issue by dovrosenberg** [foundryvtt/foundryvtt#11785]
### What happened?

```ts
export class SessionSheet extends VueApplicationMixin(DocumentSheetV2<JournalEntryPage>) {
  ...
}

DocumentSheetConfig.registerSheet(JournalEntryPage, moduleJson.id, SessionSheet, {
  types: [`${moduleJson.id}.session`],
  makeDefault: true
});
```

When I attempt to create a journal page with this type, I can see it calling `ClientDocument.getSheet()`, which properly handles the `DocumentSheetV2` case.  But as part of creating the document, `JournalSheet.render()` gets called, which then fails because `JournalSheet.getPageSheet()` (which is trying to select the right page sheet to use) only supports V1 so it's passing the wrong arguments to the `SessionSheet` constructor.

Is this a bug?  It seems like JournalSheet needs to support page sheets that are V1 or V2 even though the journal sheet itself is V1.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Need to create a JournalEntryPage subtype sheet using `DocumentSheetV2` and then create a journal page of that type.

### What core version are you reporting this for?

12.331

### Relevant log output

```shell
foundry.js:655  Error: An error occurred while rendering JournalSheet 35. Cannot read properties of null (reading 'uuid')
    at Hooks.onError (foundry.js:654:24)
    at foundry.js:5795:13Caused by: TypeError: Cannot read properties of null (reading 'uuid')
    at _SessionSheet._initializeApplicationOptions (foundry-esm.js:45783:71)
    at new ApplicationV2 (foundry-esm.js:43951:41)
    at new DocumentSheetV2 (foundry-esm.js:45707:7)
    at new VueApplication (VueApplicationMixin.mjs:12:3)
    at new _SessionSheet (Session.ts:51:14)
    at JournalSheet.getPageSheet (foundry.js:78870:15)
    at JournalSheet.isPageVisible (foundry.js:78884:17)
    at foundry.js:78532:18
    at Array.reduce (<anonymous>)
    at JournalSheet._getPageData (foundry.js:78531:71)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This is currently being worked on in V13. @Fyorl you could merge this with an existing issue or tackle it as a separate report.
