### ISSUE TITLE
Changing the type of a Document and `TypedSchemaField` does not work

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#11962]
Originally reported by [manaflower](https://discord.com/channels/170995199584108546/1184176415139184731/1303114253317832797)

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: any
**Short Description of bug**: Chat message type change causes .update() to throw an error and .system remains in old datamodel.
**Simple steps to reproduce the bug**:
1) Create two chat message datamodels
2) Create messsage of one type
3) Update the message type to the other

AE type shift works correctly, the system datamodel changes without a hitch, no errors. With chat messages however .update() errors and the .system model is still the same old until refresh.

---

Example error:
```
Uncaught TypeError: Cannot add property bastion, object is not extensible
    at SchemaField._updateCommit (foundry-esm.js:8786:21)
    at SchemaField._updateCommit (foundry-esm.js:8799:15)
    at TypeDataField._updateCommit (foundry-esm.js:11326:29)
    at SchemaField._updateCommit (foundry-esm.js:8799:15)
    at Actor5e.updateSource (foundry-esm.js:12087:21)
    at <anonymous>:1:25
```

---

Similar issue with changing the type of a `TypedSchemaField`: https://discordapp.com/channels/170995199584108546/1243227783082283140/1339748592738631770

**Comment by aaclayton** [comment]
Related to https://github.com/foundryvtt/foundryvtt/issues/11951
