### ISSUE TITLE
ActiveEffect migrateData does not allow deleting data on unlinked actors

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#11974]
### What happened?

You can not delete source data in active effect's migrateData() on unlinked actors, it instead errors.

Related to issue #11973 no doubt as this was discovered while trying to find a workaround to it

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Create datamodel with some fields
2) Add AE with that to an unlinked actor with data that should cause migration
3) Open the unlinked actor's sheet and close it

```js
export class DM extends foundry.abstract.TypeDataModel {
  static defineSchema() {
    const fields = foundry.data.fields;

    return {
      level: new fields.NumberField({
        required: false,
        //nullable: false, // This option was present for #11973, noting it here in case relevant
      }),
    };
  }

  static migrateData(source) {
    if (source.level === null) delete source.level; // <- Error happens here
  }
}

Hooks.once("init", () => {
  CONFIG.ActiveEffect.dataModels.base = DM;
});
```

### What core version are you reporting this for?

12.331

### Relevant log output

```shell
foundry-esm.js:10698 TypeError: Failed data migration for AEBaseModel: Cannot delete property 'initiative' of #<Object>
    at AEBaseModel.migrateData (ae-base.mjs:37:37)
    at AEBaseModel.migrateDataSafe (foundry-esm.js:10695:14)
    at AEBaseModel._initializeSource (foundry-esm.js:10297:31)
    at new DataModel (foundry-esm.js:10169:21)
    at new TypeDataModel (foundry-esm.js:10796:7)
    at new AEBaseModel (ae-base.mjs:6:8)
    at TypeDataField.initialize (foundry-esm.js:9796:26)
    at ActiveEffectPF._initialize (foundry-esm.js:10340:29)
    at ActiveEffectPF._initialize (foundry-esm.js:11020:13)
    at ActiveEffectPF._initialize (foundry.js:10639:13)
    at EmbeddedCollection.initialize (foundry-esm.js:5248:39)
    at EmbeddedCollectionField.initialize (foundry-esm.js:8872:18)
    at ActorCharacterPF._initialize (foundry-esm.js:10340:29)
    at ActorCharacterPF._initialize (foundry-esm.js:11020:13)
    at ActorCharacterPF._initialize (foundry.js:10639:13)
    at ActorCharacterPF._initialize (actor-base.mjs:43:11)
    at ActorCharacterPF.updateSource (foundry-esm.js:10520:35)
    at ActorDelta.updateSource (foundry.js:15371:25)
    at #handleUpdateDocuments (foundry-esm.js:56579:13)
    at async ActorCharacterPF.updateDocuments (foundry-esm.js:11473:23)
    at async ActorCharacterPF.update (foundry-esm.js:11584:23)
    at async ActorSheetPFCharacter._onSubmit (foundry.js:6665:7)
    at async ActorSheetPFCharacter._onSubmit (actor-sheet.mjs:4078:5)
    at async ActorSheetPFCharacter.submit (foundry.js:6936:5)
    at async ActorSheetPFCharacter.close (foundry.js:6909:17)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment]
The data model is constructed from source data of document, which is already sealed, and therefore the migration cannot delete any properties. We'll evaluate whether we can skip the migration in `TypeDataModel#initialize` entirely: #12863.
