### ISSUE TITLE
Redesign the behavior of `DataField#getInitialValue` to provide more consistent standards and handling for special case types like undefined, null, blank, etc...

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#11973]
# Implemented Feature
Goal of standardizing the way that `DataField#getInitialValue` works. 

## Prior State
We previously had a few different paradigms/issues with this code:

1. Some data fields (like `StringField`) hard-coded initial value logic in their `_defaults` which meant that any user-defined default would need to re-implement the same logical handling.
2. Differences in implementation (for example `StringField` vs `NumberField`) gave different priority to special values or explicit initials.
3. The responsibility of `getInitialValue` was unclearly documented. The documentation said it should throw an error if the initial value was invalid, but only in rare specific cales (like `ColorField`) was any validation done here.

## Solution Path
1. Strengthen and standardize the logic of `getInitialValue` to handle special cases and use subclass logic to add special cases where necessary. 
2. Ensure the type of data returned by `getInitialValue` is either an allowed special case like `null` or `undefined` OR that it matches the expected data type for the field (even if otherwise invalid).

# Original Report

### What happened?

AE model field with `nullable:false` and `required:false` number field causes validation to fail on unlinked actors.

On unlinked actor, AE with that model in use errors with can not be null despite the data being missing (incorrectly initialized to null instead of left as undefined as expected from required:false).

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Create active effect datamodel with following field
```js
NumberField({ required: false, nullable: false }),
```
2) Add that AE on an unlinked actor with NO system data (to trigger initial values for everything)
3) Open the actor's sheet and close it

You should see can not be null for your non-required non-null field.

The error vanishes if you add `initial:undefined` to the field, which is supposed to be there by default from `required:false`

Works fine with linked actors.

The error also occurs on world launch after that AE is created.

---

Sample code
```js
export class DM extends foundry.abstract.TypeDataModel {
  static defineSchema() {
    const fields = foundry.data.fields;

    return {
      level: new fields.NumberField({
        required: false,
        nullable: false,
      }),
    };
  }
}

Hooks.once("init", () => {
  CONFIG.ActiveEffect.dataModels.base = DM;
});
```

### What core version are you reporting this for?

12.331

### Relevant log output

```shell
foundry.js:6668 DataModelValidationError: AEBaseModel validation errors:
  initiative: may not be null
  level: may not be null
    at DataModelValidationFailure.asError (foundry-esm.js:4710:14)
    at AEBaseModel.validate (foundry-esm.js:10432:61)
    at new DataModel (foundry-esm.js:10181:12)
    at new TypeDataModel (foundry-esm.js:10796:7)
    at new AEBaseModel (ae-base.mjs:6:8)
    at TypeDataField.initialize (foundry-esm.js:9796:26)
    at ActiveEffectPF._initialize (foundry-esm.js:10340:29)
    at ActiveEffectPF._initialize (foundry-esm.js:11020:13)
    at ActiveEffectPF._initialize (foundry.js:10639:13)
    at EmbeddedCollection.initialize (foundry-esm.js:5248:39)
    at EmbeddedCollectionField.initialize (foundry-esm.js:8872:18)
    at ActorCharacterPF._initialize (foundry-esm.js:10340:29)
    at ActorCharacterPF._initialize (foundry-esm.js:11020:13)
    at ActorCharacterPF._initialize (foundry.js:10639:13)
    at ActorCharacterPF._initialize (actor-base.mjs:43:11)
    at ActorCharacterPF.updateSource (foundry-esm.js:10520:35)
    at ActorDelta.updateSource (foundry.js:15371:25)
    at #handleUpdateDocuments (foundry-esm.js:56579:13)
    at async ActorCharacterPF.updateDocuments (foundry-esm.js:11473:23)
    at async ActorCharacterPF.update (foundry-esm.js:11584:23)
    at async ActorSheetPFCharacter._onSubmit (foundry.js:6665:7)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by mkahvi** [comment]
On deeper investigation, this is not limited to unlinked actors. It's just fault of NumberField having basic `initial:null` unlike StringField which is smart about it.
