### ISSUE TITLE
Some server-side document models fail compendium migration due to invalid syntax in the hasSystemData check.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7172]
Originally in GitLab by @Fyorl

Originally reported by ghost#2000  https://discord.com/channels/170995199584108546/956306859491471420/974809105065717821

**ALL MODULES DISABLED?** true  
**Short Description of bug:** Invoking the migration of a (Macro) compendium pack causes a server side error (not sure if it also applies to other document types)  
**Simple steps to reproduce the bug:** call migrate on a (Macro) CompendiumCollection  
**Screenshots and/or console errors:**
```
FoundryVTT | 2022-05-14 01:00:01 | [error] Cannot read properties of undefined (reading 'hasSystemData')
TypeError: Cannot read properties of undefined (reading 'hasSystemData')
    at Function.migrate (file:///home/johannesloher/Games/FoundryVTT-10.263/resources/app/dist/database/backend/server-compendium.mjs:1:1622)
    at async Function._onMigrateCompendium (file:///home/johannesloher/Games/FoundryVTT-10.263/resources/app/dist/packages/world.mjs:1:11252)
    at async Socket.handleEvent (file:///home/johannesloher/Games/FoundryVTT-10.263/resources/app/dist/server/sockets.mjs:1:406)
```

**Comment by arbron** [comment]
@Fyorl This issue has popped back up for me on the latest build (V10.275):

```javascript
await game.packs.get("dnd5e.classes").migrate();
```

<img width="810" alt="Screen Shot 2022-07-28 at 12 57 09" src="https://user-images.githubusercontent.com/19979839/181626176-42ab15c2-2dc4-4f80-8441-88310cb94f3e.png">

```
FoundryVTT | 2022-07-28 12:52:39 | [error] Cannot read properties of undefined (reading 'hasSystemData')
TypeError: Cannot read properties of undefined (reading 'hasSystemData')
    at Function.migrate (…/foundryvtt/resources/app/dist/database/backend/server-compendium.mjs:1:1622)
    at async Function._onMigrateCompendium (…/foundryvtt/resources/app/dist/packages/world.mjs:1:11826)
    at async Socket.handleEvent (…/foundryvtt/resources/app/dist/server/sockets.mjs:1:470)
```

**Comment by aaclayton** [comment]
I was unable to reproduce this issue with:
```js
pack = game.packs.get("dnd5e.classes");
await pack.configure({locked: false});
await pack.migrate();
```

Presumed fixed.
