### ISSUE TITLE
Tour.fromJSON does not correctly prepend RoutePrefix to the filepath

### ISSUE THREAD

**Issue by Gensokian** [foundryvtt/foundryvtt#7560]
### Environment Details

* Foundry VTT Version: (Example 0.5.4)
  * V10 Dev3

* Operating System: [Windows, MacOS, Linux (which distro)]
  * Host: Synology NAS, using a docker container
 
* How Are You Using Foundry: [Native Application (Electron), Chrome, Firefox, Safari, Brave, etc…]
  * Chrome/Edge/Vivaldi

* Which Game System: (Example dnd5e)
  * dnd5e

* Modules Enabled?: [yes, no] If yes, please list any which might be relevant
  * None
 
### Issue Description
*Copied from [Foundry VTT Discord](https://discord.com/channels/170995199584108546/956306859491471420/999552071122571294)*

Due to the new "/tours" subdirectory, any server running the foundry prefix won't show the setup dialogue
![image](https://user-images.githubusercontent.com/9213561/180199055-1f7e8eb8-7924-44a7-bb22-7240b507ec3e.png)

**Simple steps to reproduce the bug:**
- Host a foundry with a routePrefix specified in the Config/options.json file (james, in my case)
- Do whatever is necessary to setup reverse proxy with your system web configuration. Don't want to get too into the weeds here - it worked before the upgrade to v10 (Development version 3), and works in my other v9 installs as well as v10 Development 2
- Attempt to connect to said instance
- Observe that you just land on an empty landing page with the foundry logo, with connection errors in the dev console.
**Screenshots and/or console errors:**
*commons.js:10509*
GET https://dnd.james-things.com/tours/installing-a-system.json 404

*commons.js:10520*
Uncaught (in promise) Error
    at fetchWithTimeout (commons.js:10520:13)
    at async Object.fetchJsonWithTimeout (commons.js:10536:20)
    at async SetupTour.fromJSON (foundry.js:3545:18)
    at async Setup.registerTours (setup.js:40:7)
    at async Setup.initialize (foundry.js:7277:5)

**Thesis:**
The commons.js doesn't prefix the url of the "tours/installing-a-system.json" file
![image](https://user-images.githubusercontent.com/9213561/180199066-2edc1efc-a81c-47e8-a9d7-28f8f1773c77.png)

**Comment by Gensokian** [comment]
Can confirm, this is now fixed!!
