### ISSUE TITLE
Swapping tabs in scene creation dialog throws an error

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7569]
Originally reported by Geekswordsman#3085 https://discord.com/channels/170995199584108546/956306859491471420/999021575510708384

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 10, Electron Application  
**Short Description of bug:** When creating a new scene, if you swap tabs the scene creation errors out with:

```
TypeError: Cannot read properties of null (reading 'fogUnexploredColor')  foundry.js:711 
    at #configureColors (foundry.js:38930:55)
    at CanvasColorManager.initialize (foundry.js:38886:26)
    at Canvas.draw (foundry.js:22628:23)
    at Game.initializeCanvas (foundry.js:7563:61)
    at async Game.setupGame (foundry.js:7400:5)
    at async Game._initializeGameView (foundry.js:8426:5)
    at async Game.initialize (foundry.js:7283:5)
```

**Simple steps to reproduce the bug:**  
Create a new scene.  
In the scene creation dialog, navigate to the Lighting Tab.  
Without clicking any settings in the tab, click `Save Changes`

**Comment by Fyorl** [comment]
Closing as nonrepro.
