### ISSUE TITLE
[Bug]: Error finding journalEntryPageTitle partial when editing a JE in v10

### ISSUE THREAD

**Issue by kristianserrano** [foundryvtt/foundryvtt#7606]
### What happened?

When attempting to edit a Journal Entry page in v10, I get an error in the console:
`The partial journalEntryPageTitle could not be found`

If I change the reference to that partial in the various page partials (e.g. `page-text-edit.html`) from `journalEntryPageTitle` to `templates/journal/parts/page-title.html`, the error goes away.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Open a JE, and attempt to edit a page.

### What core version are you reporting this for?

Version 10 Testing 1 (build 275)

### Relevant log output

```shell
foundry.js:711 d {description: undefined, fileName: undefined, lineNumber: undefined, endLineNumber: undefined, message: 'The partial journalEntryPageTitle could not be found', …}description: undefinedendLineNumber: undefinedfileName: undefinedlineNumber: undefinedmessage: "The partial journalEntryPageTitle could not be found"name: "Error"number: undefinedstack: "Error: The partial journalEntryPageTitle could not be found\n    at Object.h (http://127.0.0.1:30000/scripts/handlebars.min.js:27:18644)\n    at Object.c [as invokePartial] (http://127.0.0.1:30000/scripts/handlebars.min.js:27:15036)\n    at Object.eval [as main] (eval at createFunctionContext (http://127.0.0.1:30000/scripts/handlebars.min.js:29:1808), <anonymous>:17:28)\n    at c (http://127.0.0.1:30000/scripts/handlebars.min.js:27:15429)\n    at d (http://127.0.0.1:30000/scripts/handlebars.min.js:27:15744)\n    at e (http://127.0.0.1:30000/scripts/handlebars.min.js:28:22748)\n    at renderTemplate (http://127.0.0.1:30000/scripts/foundry.js:6518:10)\n    at async JournalTextPageSheet._renderInner (http://127.0.0.1:30000/scripts/foundry.js:4982:16)\n    at async JournalTextPageSheet._renderInner (http://127.0.0.1:30000/scripts/foundry.js:5541:18)\n    at async JournalTextPageSheet._renderInner (http://127.0.0.1:30000/scripts/foundry.js:59662:18)"[[Prototype]]: Error
    at Object.<anonymous> (http://127.0.0.1:30000/scripts/handlebars.min.js:27:5241)
    at b (http://127.0.0.1:30000/scripts/handlebars.min.js:27:330)
    at Object.<anonymous> (http://127.0.0.1:30000/scripts/handlebars.min.js:27:2069)
    at b (http://127.0.0.1:30000/scripts/handlebars.min.js:27:330)
    at Object.<anonymous> (http://127.0.0.1:30000/scripts/handlebars.min.js:27:1435)
    at b (http://127.0.0.1:30000/scripts/handlebars.min.js:27:330)
    at Object.<anonymous> (http://127.0.0.1:30000/scripts/handlebars.min.js:27:792)
    at b (http://127.0.0.1:30000/scripts/handlebars.min.js:27:330)
    at http://127.0.0.1:30000/scripts/handlebars.min.js:27:417
    at http://127.0.0.1:30000/scripts/handlebars.min.js:27:422
onError @ foundry.js:711
(anonymous) @ foundry.js:4768
Promise.catch (async)
render @ foundry.js:4766
render @ foundry.js:6033
_onEditPage @ foundry.js:60671
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:4798 Foundry VTT | Rendering JournalTextPageSheet
foundry.js:6457 Foundry VTT | Retrieved and compiled template templates/journal/parts/page-title.html
foundry.js:6457 Foundry VTT | Retrieved and compiled template templates/journal/page-text-edit.html
```
```


### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by kristianserrano** [comment]
Nevermind. It's an issue with my module. 🤦‍♂️
