### ISSUE TITLE
Allow renderTemplate() to render named templates

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#8150]
### User Experience

renderTemplate() currently insists the first parameter is a file, making named templates fail to render with it as demonstrated:
```js
await loadTemplates({ 'myLittleTemplate': "modules/somewhere/out/there.hbs" });
const content = await renderTemplate("myLittleTemplate", {myData});
```
which simply throws an error at you:
```
foundry.js:6748 Uncaught (in promise) Error: You are only allowed to load template files with an extension in [html,handlebars,hbs]
[No packages detected]
    at i.<anonymous> (foundry.js:6748:41)
    at i.value (socket.js:309:17)
    at i.value (socket.js:239:22)
    at x.emit (index.mjs:136:20)
    at s.value (manager.js:200:14)
    at x.emit (index.mjs:136:20)
    at a.value (index.js:119:51)
    at s.value (manager.js:192:22)
    at x.emit (index.mjs:136:20)
    at a.value (socket.js:323:26)
    at x.emit (index.mjs:136:20)
    at i.value (transport.js:104:14)
    at i.value (transport.js:97:14)
    at ws.onmessage (websocket.js:79:40)
```

It'd be nice if it allowed the named templates also.

This is minor convenience thing really, mostly useful for game systems but some larger modules can also benefit from it.

**Comment by mkahvi** [comment]
Simple solution would be to check cache first for the template and then check if it's in valid format.
