### ISSUE TITLE
Missing/invalid *.pem files cause Foundry to crash silently on launch

### ISSUE THREAD

**Issue by rocketgarden** [foundryvtt/foundryvtt#8342]
### What happened?

If foundry is pointed to invalid .pem files for its SSL config, it refuses to launch. Specifically in this case, if certbot's symlinks in the `Certbot/live` directory are broken because they point to an invalid target. The observed behavior is that FoundryVTT shows up in the task manager for a second and then vanishes with no visible window opening.
Running via command line yields the log output below, which pretty decisively points to crashing on invalid PEM files

Desired behavior: Foundry launches but throws a visible error about the invalid .pem files, preferably allowing access to settings to reconfigure SSL

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Configure foundry to use SSL and .pem files using symlinks for the *.pem files. e.g. point directly at `Certbot/live` folder
2) Delete the source fullchain.pem and privkey.pem files in certbot/archive (or rename the folder)
3) observe the symlinks don't point anywhere now
4) Try to launch foundry
5) Observe that foundry will not start no matter how many times I click it
6) Be sad
7) (un-delete/un-rename your *.pem files)

### What core version are you reporting this for?

Version 10 Build 287

### Relevant log output

```shell
[error] A fatal error occurred while trying to start the Foundry Virtual Tabletop server: ServerConfiguration Model Validation Errors
[ServerConfiguration.sslCert]: File path "C:/Certbot/live/redacted.url/fullchain.pem" does not exist
[ServerConfiguration.sslKey]: File path "C:/Certbot/live/redacted.url/privkey.pem" does not exist
Error: A fatal error occurred while trying to start the Foundry Virtual Tabletop server: ServerConfiguration Model Validation Errors
[ServerConfiguration.sslCert]: File path "C:/Certbot/live/redacted.url/fullchain.pem" does not exist
[ServerConfiguration.sslKey]: File path "C:/Certbot/live/redacted.url/privkey.pem" does not exist
    at SchemaField._validateType (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:480:13)
    at SchemaField.validate (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/data/fields.mjs:207:35)
    at ServerConfiguration.validate (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:282:33)
    at new DataModel (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/data.mjs:59:24)
    at new ApplicationConfiguration (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/config.mjs:36:1)
    at new ServerConfiguration (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/core/config.mjs:1:908)
    at Function.load (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/core/config.mjs:1:3774)
    at _initializeCriticalFunctions (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/init.mjs:1:2671)
    at async Module.initialize (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/init.mjs:1:1564)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment]
Since foundry works fine without SSL certificates, we can relegate this to a warning and have foundry start up without SSL if it can't locate the certificates. However, some users may view it as a security risk if foundry unexpectedly launches on an insecure connection, so I'm not sure.

**Comment by Fyorl** [comment]
We have determined that this is behaving correctly, so we are closing it as wontfix.
