### ISSUE TITLE
ProseMirror breaks with certain rich text pastes

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#8429]
### What happened?

Copy-pasting text from rich text source into prosemirror causes the editor to become broken.

```html
<span style="font-family: Whitney, "Helvetica Neue", Helvetica, Arial, sans-serif">pasted text</span>
```

After this error occurs, the prosemirror editor fails to display the toolbar when editing. Only way to recover from this is to update the text field via manual actor.update() or similar.

Obviously caused by the bad quotes, but why is the paste adding them?

Here's demonstration video of copypasting text from Discord:  
[prosemirror-paste.webm](https://user-images.githubusercontent.com/8120158/197977420-173cdf85-d182-4975-8d8e-8af8d19eee90.webm)

Original Discord report: <https://discord.com/channels/170995199584108546/956307084931112960/1031272534026494233>  
The pasted text is from this message: <https://discord.com/channels/170995199584108546/956307084931112960/1034743946347286618>

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Paint regular text in Discord (not URLs)
2) ctrl-c copy it
3) ctrl-v it in prosemirror
4) Save
5) Try to edit it again

### What core version are you reporting this for?

10.288

### Relevant log output

```shell
prosemirror.js:3440 Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': 'neue",' is not a valid attribute name.
    at DOMSerializer.renderSpec (http://localhost:30000/foundryDev/scripts/prosemirror.js:3440:31)
    at MarkViewDesc.create (http://localhost:30000/foundryDev/scripts/prosemirror.js:7621:36)
    at ViewTreeUpdater.syncToMarks (http://localhost:30000/foundryDev/scripts/prosemirror.js:8203:47)
    at http://localhost:30000/foundryDev/scripts/prosemirror.js:7771:23
    at iterDeco (http://localhost:30000/foundryDev/scripts/prosemirror.js:8403:15)
    at NodeViewDesc.updateChildren (http://localhost:30000/foundryDev/scripts/prosemirror.js:7761:11)
    at new NodeViewDesc (http://localhost:30000/foundryDev/scripts/prosemirror.js:7666:20)
    at NodeViewDesc.create (http://localhost:30000/foundryDev/scripts/prosemirror.js:7710:22)
    at ViewTreeUpdater.addNode (http://localhost:30000/foundryDev/scripts/prosemirror.js:8293:66)
    at http://localhost:30000/foundryDev/scripts/prosemirror.js:7782:27
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by mkahvi** [comment]
This is still affecting me with b290

**Comment by Feu-Secret** [comment]
Reopening this issue.
Related to: https://discord.com/channels/170995199584108546/956306859491471420/1040800727905357966
See thread here: https://discord.com/channels/170995199584108546/956307084931112960/1041649564198907934
