### ISSUE TITLE
Launching Foundry with demo flag produces TypeError

### ISSUE THREAD

**Issue by jsavko** [foundryvtt/foundryvtt#8453]
### What happened?

When launch foundry via node with the `--demo` argument node returns a TypeError:

```
D:\FoundryVTT10>node resources\app\main.js --dataPath=D:/FoundryData --demo
FoundryVTT | 2022-10-31 10:53:41 | [info] Running on Node.js - Version 16.15.0
FoundryVTT | 2022-10-31 10:53:41 | [info] Foundry Virtual Tabletop - Version 10 Build 288
FoundryVTT | 2022-10-31 10:53:41 | [info] User Data Directory - "D:/FoundryData"
FoundryVTT | 2022-10-31 10:53:41 | [error] A fatal error occurred while trying to start the Foundry Virtual Tabletop server: The "path" argument must be of type string. Received type boolean (true)
TypeError [ERR_INVALID_ARG_TYPE]: A fatal error occurred while trying to start the Foundry Virtual Tabletop server: The "path" argument must be of type string. Received type boolean (true)
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:429:7)
    at ServerConfiguration._initializeDemoMode (file:///D:/FoundryVTT10/resources/app/dist/core/config.mjs:1:3158)
    at ServerConfiguration.initialize (file:///D:/FoundryVTT10/resources/app/dist/core/config.mjs:1:2279)
    at _initializeCriticalFunctions (file:///D:/FoundryVTT10/resources/app/dist/init.mjs:1:2680)
    at async Module.initialize (file:///D:/FoundryVTT10/resources/app/dist/init.mjs:1:1564)```

When providing --demo with a path `--demo=demo.json` the server starts fine. 
```D:\FoundryVTT10>node resources\app\main.js --dataPath=D:/FoundryData --demo=demo.json
FoundryVTT | 2022-10-31 10:57:15 | [info] Running on Node.js - Version 16.15.0
FoundryVTT | 2022-10-31 10:57:15 | [info] Foundry Virtual Tabletop - Version 10 Build 288
FoundryVTT | 2022-10-31 10:57:15 | [info] User Data Directory - "D:/FoundryData"
FoundryVTT | 2022-10-31 10:57:15 | [info] Application Options:
{
  "port": 30000,
  "upnp": false,
  "fullscreen": false,
  "hostname": null,
  "localHostname": null,```


### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

launch foundry via node with --demo arg

### What core version are you reporting this for?

10.288

### Relevant log output

_No response_

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
This was an intentional change in V10, if using the `--demo` CLI flag you have to pass a path which contains the demo configuration.

Alternatively, if you always want to run in demo mode you can encode the demo parameters into the main `options.json` file as an inner-object of the `demo` key.

**Comment by jsavko** [comment]
The documentation on https://foundryvtt.com/article/configuration/ should be updated then
