### ISSUE TITLE
Replacing title of popOut window throw Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'textContent')

### ISSUE THREAD

**Issue by crnormand** [foundryvtt/foundryvtt#8506]
### What happened?

The image previewer module throws up a quick preview of the icon being hovered over.   It can usually show 1 or two images, and then throws the exception.  Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'textContent')

There is nothing I can do in the image previewer module.   The error occurs in Foundry because the results of a query are assume to contain data... and in this case, it doesn't.   I am assuming the asynchronous nature of the preview window opening may be the culprit 

The exception occurs in the _replaceHTML() method:

```
  _replaceHTML(element, html) {
    if ( !element.length ) return;

    // For pop-out windows update the inner content and the window title
    if ( this.popOut ) {
      element.find(".window-content").html(html);
      const t = element.find(".window-title");
      t[0].childNodes[0].textContent = this.title;   // THE EXCEPTION IS THROWN HERE
    }

    // For regular applications, replace the whole thing
    else {
      element.replaceWith(html);
      this._element = html;
    }
  }
```

The exception is thrown If **t** is null, or **t[0]** has no children nodes.  

This is the fix:

```
  _replaceHTML(element, html) {
    if ( !element.length ) return;

    // For pop-out windows update the inner content and the window title
    if ( this.popOut ) {
      element.find(".window-content").html(html);
      const t = element.find(".window-title");
      if (!!t[0] && !!t[0].childNodes[0]) t[0].childNodes[0].textContent = this.title;
    }

    // For regular applications, replace the whole thing
    else {
      element.replaceWith(html);
      this._element = html;
    }
  }
```

Note: if not t[0] or not t[0].childNodes[0] there is nothing to set anyway, so forcing the textContent produces the error.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Load the image previewer module https://foundryvtt.com/packages/image-previewer,
Open a filepicker for an Icon (edit a chat macro and click on the icon to pick a new one).
Quickly mouse over the entries.
The exception will occur.

### What core version are you reporting this for?

Version 10 (build 288)

### Relevant log output

```shell
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'textContent')
    at ImagePreviewer._replaceHTML (foundry.js:5250:38)
    at ImagePreviewer._render (foundry.js:5077:32)
```

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by crnormand** [comment]
I am still trying to support the image previewer module (I've had requests to make it work in V10).    The popup window being created by the image previewer is correct.   It contains a 'window-title' element.
