### ISSUE TITLE
Build the precompiled binaries for LevelDB and classic level using a lesser version of the GLIBC library to support a wider range of environments.

### ISSUE THREAD

**Issue by buttonpushertv** [foundryvtt/foundryvtt#8847]
### What happened?

Attempting to install node.js version of FVTT v11.292 Prototype, application fails to launch with this error:
```
node: internal/modules/cjs/loader:1302
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /mnt/SSD/dietpi_userdata/foundryvtt/resources/app/node_modules/classic-level/prebuilds/linux-arm/node.napi.armv7.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1302:18)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at load (/mnt/SSD/dietpi_userdata/foundryvtt/resources/app/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/mnt/SSD/dietpi_userdata/foundryvtt/resources/app/node_modules/classic-level/binding.js:1:43)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```
_This may be a larger issue. It does not appear that GLIBCXX 3.4.29 is available to install on Raspbian. Now this may be a temporary issue as new versions get rolled out, but, based on preliminary research, updating this library may be more difficult than it seems._

Is it just a matter of recompiling some of the binaries with a different GLIB library dependence?

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

1. Follow these instructions: https://foundryvtt.wiki/en/setup/linux-installation to install FVTT v11
2. Attempt to launch the app via command: `node foundry/resources/app/main.js --dataPath=/home/<user>/foundryuserdata`
3. Get error message listed above.

### What core version are you reporting this for?

Version 11.292 (Build 292)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by peteraldous** [comment]
I came across this issue (self-hosted on raspbian, which I just updated to bookworm. It now has the specified version of GLIBCXX. I still had issues, so I rebuilt classic-level from source. I got an error about GLIBC (not GLIBCXX). After some digging, I discovered that the 18/stable channel of node in snap is based on core20, not core22.  Updating node to 20/stable fixed it. The more you know!
