### ISSUE TITLE
Canvas breaks after restoration of lost webgl context

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8989]
### What happened?

The blend modes added by core must be added after each `contextChange`: the state manager recreates the `blendModes` on `contextChange`.

Suggested solution:
```js
    const contextChange = {
      contextChange: (gl) => {
        for ( let [k, v] of Object.entries(BLEND_MODES) ) {
          const pos = this.app.renderer.state.blendModes.push(v) - 1;
          PIXI.BLEND_MODES[k] = pos;
          PIXI.BLEND_MODES[pos] = k;
        }
        // Fix a PIXI bug with custom blend modes
        this.#mapPremultipliedBlendModes();
      }
    };
    contextChange.contextChange(this.app.renderer.gl);
    this.app.renderer.runners.contextChange.add(contextChange);
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Run:
```js
canvas.app.renderer.context.extensions.loseContext.loseContext()
```

### What core version are you reporting this for?

Version 11 Prototype 2 (build 293)

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Jr.setBlendMode (index.js:89:1)
    at Array.checkBlendMode (index.js:89:1)
    at Jr.set (index.js:89:1)
    at Zt.drawBatches (isMobile.js:120:76)
    at Zt.flush (isMobile.js:120:76)
    at Zt.stop (isMobile.js:120:76)
    at Fr.setObjectRenderer (settings.mjs:5:50)
    at Fr.flush (settings.mjs:5:50)
    at pn.renderAdvanced (index.js:126:1)
    at pn.render (index.js:126:1)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Feu-Secret** [comment]
Good catch. We will hook on the context loss.
