### ISSUE TITLE
Deleting a tile after resize throws an error

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9161]
Originally reported by grape_juice#2539 https://discord.com/channels/170995199584108546/956306859491471420/1086634220694294538

**ALL MODULES DISABLED?** true  
**Short Description of bug:** deleting a tile after resize produces errors  
**Simple steps to reproduce the bug:** open tile browser, drop a tile, resize tile, delete tile  
**Screenshots and/or console errors:**

```
display.min.mjs:8 Uncaught TypeError: Cannot read properties of null (reading 'scale')
    at ResizeHandle.get (display.min.mjs:8:8955)
    at Tile._onHandleHoverOut (foundry.js:45398:12)
    at Tile._onHoverOut (foundry.js:45296:35)
    at MouseInteractionManager.callback (foundry.js:27813:45)
    at MouseInteractionManager._handleMouseOut (foundry.js:27952:17)
    at a.emit (index.js:181:35)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerOverOut (interaction.min.mjs:8:18331)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
```

[scaledelete.webm](https://user-images.githubusercontent.com/207433/229527718-5ca9c0ea-ca3b-4447-84b0-e68eabb3dfb2.webm)

**Comment by aaclayton** [comment]
@fyorl did this come from v11 feedback? or v10 feedback? Do we know which release this issue applies to? Some significant things changed here with interaction in v11.

**Comment by Fyorl** [comment]
> @Fyorl did this come from v11 feedback? or v10 feedback? Do we know which release this issue applies to? Some significant things changed here with interaction in v11.

This was from the v10 bug channel

**Comment by aaclayton** [comment]
Confirmed as resolved in V11 via other related fixes.
