### ISSUE TITLE
Secret Text blocks are not correctly hidden from users in the DSA5 system.

### ISSUE THREAD

**Issue by HenrikSonntag** [foundryvtt/foundryvtt#9182]
### What happened?

The mystery function on the text does not work on the actors.
If I mark a text in the actor's background story as a secret then this is not hidden from the players. There is also no "show button" for me as SL. It doesn't matter what permission the player has. With the notes, on the other hand, everything works fine. I don't know if it's relevant but I use The Forge and players the German version of The dark eye
see screenshot from player view:
![Unbenannt](https://user-images.githubusercontent.com/95576279/230889439-1fa50f14-83ec-4de5-bb3b-6cd7c283a6e1.JPG)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

System: The dark eye 
![Unbenannt](https://user-images.githubusercontent.com/95576279/230889705-31cd9e37-5b9c-4480-beef-c1d1040913a4.JPG)

Provider: The Forge

### What core version are you reporting this for?

Version 10 

### Relevant log output

```shell
Foundry VTT | Viewing Scene Landingpage
foundry.js:23648 Foundry VTT | Drawing game canvas for scene Landingpage
tokenmagic.js:186 TokenMagic | Hook -> canvasInit
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/dice/roll.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/dice-calculator/templates/tray.html
foundry.js:25946 Foundry VTT | Loaded icons/svg/door-secret-outline.svg (2%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/falling.svg (5%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/silenced.svg (7%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/paralysis.svg (10%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/sleep.svg (12%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/down.svg (14%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/sword.svg (17%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/stoned.svg (19%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/fire.svg (21%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/terror.svg (24%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/bones.svg (26%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/sound-off.svg (29%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/cowled.svg (31%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/hazard.svg (33%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/circle.svg (36%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/radiation.svg (38%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/up.svg (40%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/net.svg (43%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/combat.svg (45%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/aura.svg (48%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/padlock.svg (50%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/skull.svg (52%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/light.svg (55%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/light-off.svg (57%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/explosion.svg (60%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/sound.svg (62%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/door-closed-outline.svg (64%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/door-open-outline.svg (67%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/door-locked-outline.svg (69%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/blood.svg (71%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/unconscious.svg (74%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/blind.svg (76%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/poison.svg (79%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/biohazard.svg (81%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/deaf.svg (83%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/cave.svg (86%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/anchor.svg (88%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/daze.svg (90%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/ice-aura.svg (93%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/tower.svg (95%)
foundry.js:25946 Foundry VTT | Loaded icons/svg/pawprint.svg (98%)
foundry.js:25946 Foundry VTT | Loaded https://assets.forge-vtt.com/6256e9b4e2fca98111b9d154/Henrik/AventurienTisch_RvB.jpg (100%)
foundry.js:30347 Foundry VTT | Drawing the WeatherEffects canvas layer
foundry.js:30347 Foundry VTT | Drawing the ParticleEffectsLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the CanvasBackgroundAlterationEffects canvas layer
foundry.js:30347 Foundry VTT | Drawing the CanvasIlluminationEffects canvas layer
foundry.js:30347 Foundry VTT | Drawing the CanvasColorationEffects canvas layer
foundry.js:30347 Foundry VTT | Drawing the CanvasVisibility canvas layer
foundry.js:30347 Foundry VTT | Drawing the GridLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the DrawingsLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the TemplateLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the TilesLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the WallsLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the TokenLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the SoundsLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the LightingLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the NotesLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the ControlsLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the SpecialEffectsLayer canvas layer
foundry.js:30347 Foundry VTT | Drawing the DSAMenuLayer canvas layer
foundry.js:5099 Foundry VTT | Rendering HeadsUpDisplay
token-attacher.js:1097 Token Attacher | Tools added.
foundry.js:5099 Foundry VTT | Rendering SmallTimeApp
tokenmagic.js:186 TokenMagic | Hook -> canvasReady
gm-notes.js:218 gm-notes | Module[gm-notes] ready hook complete
tokenmagic.js:186 TokenMagic | Hook -> ready
logger.js:51 Tokenizer | INFO > Ready Hook Called
foundry.js:5099 Foundry VTT | Rendering CompendiumFolderDirectory
foundry.js:5099 Foundry VTT | Rendering ControlManager
foundry.js:5099 Foundry VTT | Rendering TokenHotbar2
foundry.js:5099 Foundry VTT | Rendering MainApp
foundry.js:747 TypeError: An error occurred while rendering ControlManager 7. Cannot set properties of undefined (setting 'active')
[Detected 1 package: lib-df-buttons]
    at ControlManager.getData (ControlManager.ts:168:15)
    at async ControlManager._render (foundry.js:5108:18)
    at async ControlManager._render (ControlManager.ts:263:3)
onError @ foundry.js:747
foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/hud/hud.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/smalltime/templates/smalltime.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/dsa5-herbarium/templates/plant-inventory.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/dsa5-herbarium/templates/plant-item-identified.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/dsa5-herbarium/templates/plant-item-unidentified.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/dsa5-herbarium/templates/chat/regionModifiers.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/dsa5-herbarium/templates/plantgen/plantpick.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/compendium-folders/templates/compendium-directory.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/foundryvtt-simple-calendar/templates/main.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/dsa5/templates/status/tokenHotbar.html
3foundry.js:6887 Foundry VTT | Retrieved and compiled template templates/app-window.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/dsa5/templates/system/didyouknow.html
dsa5.bundle.js:2 loading Array(1)
_callee4$ @ dsa5.bundle.js:2
11foundry.js:63204 Font family "custom" failed to load.
loadFont @ foundry.js:63204
dsa5.bundle.js:2 Preloading forced DSA dice assets
(anonym) @ dsa5.bundle.js:2
dsa5.bundle.js:2 loading Array(1)
_callee4$ @ dsa5.bundle.js:2
foundry.js:80290 Foundry VTT | Activating pending audio playback with user gesture.
foundry.js:5099 Foundry VTT | Rendering ActorSheetdsa5Character
foundry.js:6887 Foundry VTT | Retrieved and compiled template systems/dsa5/templates/actors/npc-limited.html
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/dsa5-compendium/templates/hitzone-selector.html
```

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Plushtoast** [comment]
It is 2.) 
I already have a fix for the next patch of the system.
You can ignore (close) this issue

Regards Huepfklotz

**Comment by HenrikSonntag** [comment]
thanks everyone for the quick and helpful reply. In fact, I give the players observer rights to the actors they have already met. there are only problems if there is background information in ready-made actors which the players cannot know. therefore it would help to keep the information secret.
