### ISSUE TITLE
ChatMessage validation failing when `->` present in message

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9326]
https://discord.com/channels/170995199584108546/1065764070680186930/1102187918778449930

Short Description of bug: Whenever I call the ChatMessage.create(_message) function, no thing happens and I get error messages in the console. I could narrow it down to having "->" in the HTML text in the message content, as soon as I remove the ">" character in there, it works as expected.
Simple steps to reproduce the bug: 
Create a message with the function above and the following content: <span class="details"> -> WHATEVER</span>
It has trouble with "&nbsp;" too

Screenshots and/or console errors:
```
commons.js:7841 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Tokenizer.stateBeforeEntity (home/turu/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:584:47)
    at Tokenizer.parse (home/turu/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:848:26)
    at Tokenizer.write (home/turu/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:159:14)
    at Parser.write (home/turu/foundryvtt/resources/app/node_modules/htmlparser2/lib/Parser.js:459:28)
    at sanitizeHtml (home/turu/foundryvtt/resources/app/node_modules/sanitize-html/index.js:588:10)
    at cleanHTML (/home/turu/foundryvtt/resources/app/dist/database/validators.mjs:1:204)
    at HTMLField.sanitizeHTMLField [as sanitize] (/home/turu/foundryvtt/resources/app/dist/database/sanitization.mjs:1:1235)
    at ChatMessage._sanitizeFields (/home/turu/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7186)
    at ChatMessage.sanitizeUserInput (/home/turu/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:6908)
    at ServerDatabaseBackend._createDocuments (/home/turu/foundryvtt/resources/app/dist/database/backend/server-backend.mjs:1:2341)
    ```

**Comment by Fyorl** [comment]
I think this is probably the same cause as #9330, the final error message looks the same. Maybe an update to the `parse5` library has introduced a bug? Or fixed a bug where HTML parsing was too lenient? The reports suggest that certain text content that worked in v10 is now throwing validation errors in v11. Some additional context [here](https://discord.com/channels/170995199584108546/1065764029278212230/1102187301624348732).

**Comment by Fyorl** [comment]
The root cause of this issue is that some `node_modules` dependencies (in this case, `htmlparser2`), have their own interior `node_modules` dependencies. When updating, foundry is not able to easily remove those interior folders as they might be in use, which is the same issue as #9214. In #9214's case, we have implemented a short-term workaround only, but it does not extend to this issue.

What is happening here is that the runtime (node or electron) is prioritising the old dependency that still exists in the interior `node_modules`, instead of using the newer dependency that is a sibling. Without being able to delete that interior `node_modules`, the foundry updater cannot resolve this issue itself. It is a reasonably rare occurrence, and until we can resolve it in the general case by way of a standalone updater, the solution is to install a clean version of v11 foundry from the website, which we recommend anyway as our minimum electron requirements have also increased.
