### ISSUE TITLE
Surface additional details for Invalid Manifest error

### ISSUE THREAD

**Issue by thre-z** [foundryvtt/foundryvtt#9358]
### User Experience

The Invalid Manfiest error is the same regardless of the underlying reasons for the error. I feel like this could be improved in order to provide a better experience or more context for error troubleshooting. 

```
Error: Unable to load valid world manifest data from "."
The requested manifest at "." did not provide world manifest data.
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:2094)
```

There are multiple underlying issues that generate the error: 

- Failed connection or malformed URL
  - No network connectivity or DNS issue or wrong address
  - A malformed URL or unsupported protocol (ie: just 'adfasdf' as the URL)
- HTTP error
  - HTTP 404, 403, etc
-  Non-JSON document returned
   - Hitting the github page about the manifest rather than the raw manifest file
- Wrong type of JSON document returned
  - Module manifest in the World installation, etc
  - Non-manifest JSON file

As it stands now, it can be very difficult to differentiate a local issue (DNS or github rate limiting or filtering) vs a manifest issue (installing a module manifest as a world). 

Providing some additional context to understand which of the situations above would be very useful to help users understand what the issue may be, and a path forward in troubleshooting. 

Even simply surfacing the HTTP error or connection error in those situations would help understand the issue at hand.

**Comment by somanyrobots** [comment]
will second this, debugging an invalid manifest is entirely trial and error (and the official documentation is very lacking here, which makes it worse)
