### ISSUE TITLE
Certain LevelDB packs fail to open on certain systems

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9603]
Originally reported by Conworld Jack#4444 https://discord.com/channels/170995199584108546/1065764070680186930/1116829425753915493

**ALL MODULES DISABLED?** false  
**OS, Hosting, Browser (if applicable)**: Ubuntu 22.04, Cloud/DigitalOcean, Chromium  
**Short Description of bug**: LevelsAutoCover prevents world loading for me and me alone in V11  
**Simple steps to reproduce the bug**:

1. Enable LevelsAutoCover
2. Be prevented from loading
3. Observe grey screen

**Screenshots and/or Console Errors**

```
Foundry.js:15853 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sort')
    at new CompendiumCollection (foundry.js:15853:37)
    at Game.initializePacks (foundry.js:8760:27)
    at Game.setupGame (foundry.js:8643:10)
    at async Game._initializeGameView (foundry.js:9925:5)
```
Prior discussion of this issue with module creator theripper93 here: https://discord.com/channels/844900867240361984/1116407912676466780

They could not reproduce the error, and directed me to make a bug report here.

A fresh install of foundry on a new server, as well as freshly installed module package, produces the exact same error.

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/32fd13dc-ee25-438b-850f-8738479fb9ff)

**Comment by Fyorl** [comment]
When I looked into this, I wasn't able to reproduce the issue with the module in question; the pack loaded fine. I also tried it on a Fedora 38 install and had no issue there either, which rules out OS line-endings at least. It could be architecture related, but I believe the reporter said (in other channels) that they only had this issue with some packages and not others.

**Comment by Fyorl** [comment]
Closing as nonrepro. As best we can tell, this is something unique to the reporter's setup, and we have not been able to identify what exactly that might be.
