### ISSUE TITLE
Dropping a Document to the sidebar using raw `data` throws an error if no `_id` is present

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9650]
Originally reported by manaflower https://discord.com/channels/170995199584108546/1065764070680186930/1119933099208343613

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable)**: any  
**Short Description of bug**: Drag&drop event with `data`  to sidebar errors if the data doesn't have `_id`  
**Simple steps to reproduce the bug**:
1) Create a dragStart listener that fills in item data but does NOT include _id.
2) Use that drag handle to drag an item into the sidebar.

The item is created correctly, but causes the following error (tested multiple systems):
**Screenshots and/or console errors**:
```
Foundry.js:13571 Uncaught (in promise) Error: You must provide an _id for every object in the update data Array.
    at #preUpdateDocumentArray (foundry.js:13571:32)
    at async ClientDatabaseBackend._updateDocuments (foundry.js:13383:22)
    at async Item5e.updateDocuments (commons.js:7892:23)
    at async Item5e.sortRelative (foundry.js:14216:29)
```

**Comment by Fyorl** [comment]
Seems this was fixed by the resolution to #9620
