### ISSUE TITLE
`ItemDirectory`'s "View Item Artwork" context menu option accesses deprecated `Item#data` property

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#9710]
### What happened?

```js
  /** @override */
  _getEntryContextOptions() {
    const options = super._getEntryContextOptions();
    return [
      {
        name: "ITEM.ViewArt",
        icon: '<i class="fas fa-image"></i>',
        condition: li => {
          const item = game.items.get(li.data("documentId"));
          return item.img !== CONST.DEFAULT_TOKEN;
        },
        callback: li => {
          const item = game.items.get(li.data("documentId"));
          new ImagePopout(item.data.img, {     //❗
            title: item.name,
            uuid: item.uuid
          }).render(true);
        }
      }
    ].concat(options);
  }
  ```

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Right click an item in the item directory and select "View Item Artwork" from the context menu.

### What core version are you reporting this for?

11.304

### Relevant log output

```shell
Error: You are accessing the WeaponPF2e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1993:19)
    at WeaponPF2e._logV10CompatibilityWarning (commons.js:8445:14)
    at get data [as data] (commons.js:8333:24)
    at Object.callback (foundry.js:86288:32)
    at #onClickItem (foundry.js:64570:11)
    at HTMLElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
Amazed that one of these has survived so long! A last of its kind!

**Comment by stwlam** [comment]
![museum](https://github.com/foundryvtt/foundryvtt/assets/106829671/34c69ac1-c459-445c-ae6f-5a5585931183)

**Comment by krbz999** [comment]
> Amazed that one of these has survived so long! A last of its kind!

\*coughs\*

```js
  /**
   * Handle repositioning of placed objects when the Scene dimensions change
   * @private
   */
  _repositionObjects(sceneUpdateData) {
  <... snip ... >
  
    // Walls are two points
    sceneUpdateData["walls"] = this.walls.map(w => {
      const c = w.data.c; // <----- OH NO!
      const p1 = adjustPoint(c[0], c[1]);
      const p2 = adjustPoint(c[2], c[3]);
      return {_id: w.id, c: [p1.x, p1.y, p2.x, p2.y]};
    });

    return sceneUpdateData;
}
```

![image](https://github.com/foundryvtt/foundryvtt/assets/50169243/962924aa-ee12-43f0-bab9-9f251dac5dc4)
