### ISSUE TITLE
V11: Failed to connect to database "actors"

### ISSUE THREAD

**Issue by Schaltfehler** [foundryvtt/foundryvtt#9766]
### What happened?

I upgrade from V10 to V11. 
When using V11 I can not open and migrate any of my worlds.

I am using the Electron App on MacOS Ventura 13.4.1 with Version 11 Build 305 previous used version was Version 10 Build 10.291.

The User Data Directory stored on a network drive in my local network.
Accessing Network Storage is granted by MacOS.
List of Worlds, GameSystems and Modules are shown.

I run Resources/app/main.js directly with node.js as well which results in the same problem.

I also noticed that game system and modules often fail to update via the UpdateAll Button. In those cases I have to delete and reinstall the Game System in order to update to the latest version.

When User Data Directory is local migration and update works without problems. V10 didn't had any issue with the User Data Directory been stored on a network drive.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Set User Data Directory to be on a network drive
- Create a world under V10
- Reinstall VTT with V11
- V11 and try to install updated game systems
- Try to open and migrate a world 

### What core version are you reporting this for?

Version 11 Build 305 

### Relevant log output

```shell
FoundryVTT | 2023-07-15 15:46:36 | [error] Failed to connect to database "actors": Database is not open
FoundryVTT | 2023-07-15 15:46:36 | [error] Failed to connect to database "actors": Database is not open
Error: Failed to connect to database "actors": Database is not open
    at maybeOpened (/Applications/Foundry Virtual Tabletop.app/Contents/Resources/app/node_modules/abstract-level/abstract-level.js:133:18)
    at /Applications/Foundry Virtual Tabletop.app/Contents/Resources/app/node_modules/abstract-level/abstract-level.js:160:13
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
FoundryVTT | 2023-07-15 15:46:36 | [error] Database is not open
Error: Database is not open
    at LevelDatabase.keys (/Applications/Foundry Virtual Tabletop.app/Contents/Resources/app/node_modules/abstract-level/abstract-level.js:697:13)
    at LevelDatabase.compactFull (file:///Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/dist/database/backend/level-database.mjs:1:1647)
    at LevelDatabase.close (file:///Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/dist/database/backend/level-database.mjs:1:1171)
    at Module.disconnect (file:///Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/dist/database/database.mjs:1:1658)
    at World.deactivate (file:///Applications/Foundry%20Virtual%20Tabletop.app/Contents/Resources/app/dist/packages/world.mjs:1:11206)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by unsoluble** [comment]
It’s not surprising that v11’s LevelDB files cannot be located on a network share.

**Comment by Schaltfehler** [comment]
Means this is not a bug but a limitation of LevelDB?

**Comment by zuedev** [comment]
I'm also getting this error except I'm not using network shares.

Here's my log:
```
FoundryVTT | 2023-07-16 15:46:48 | [info] Software license verification succeeded
FoundryVTT | 2023-07-16 15:46:48 | [error] Failed to connect to database "actors": Database is not open
/home/foundry/resources/app/node_modules/abstract-level/abstract-level.js:133
        callback(new ModuleError('Database is not open', {
                 ^


ModuleError: Failed to connect to database "actors": Database is not open
    at maybeOpened (/home/foundry/resources/app/node_modules/abstract-level/abstract-level.js:133:18)
    at /home/foundry/resources/app/node_modules/abstract-level/abstract-level.js:160:13
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'LEVEL_DATABASE_NOT_OPEN',
  cause: [Error: IO error: /data/Data/worlds/maledictum-2023/data/actors/MANIFEST-000016: No such file or directory] {
    code: 'LEVEL_IO_ERROR'
  }
}


Node.js v18.16.1
Launcher | 2023-07-16 15:46:48 | [error] Node process exited with code 1
```

**Comment by unsoluble** [comment]
This is best investigated on the discord — hit us up in #troubleshooting.
