### ISSUE TITLE
write EIO","stack

### ISSUE THREAD

**Issue by ppovolotsky** [foundryvtt/foundryvtt#9963]
### What happened?

OS Ubuntu 22.04.2 LTS Jammy
Foundry last stable, clear install, after logout putty session where node was launched start spamming errors in log
didnt met it on build 10, last played 27.08.2023 no errors like bellow
This error didnt occure if foundry was launched via system service

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

login to server console via putty
make clear installation build 11 version 308
launch foundry 
> node resources/app/main.js --dataPath=/home/foundry/foundryvtt

logout putty

### What core version are you reporting this for?

build 11 version 308

### Relevant log output

```shell
{"code":"EIO","errno":-5,"level":"error","message":"write EIO","stack":"Error: write EIO\n    at afterWriteDispatched (node:internal/stream_base_commons:160:15)\n    at writeGeneric (node:internal/stream_base_commons:151:3)\n    at Socket._writeGeneric (node:net:931:11)\n    at Socket._write (node:net:943:8)\n    at writeOrBuffer (node:internal/streams/writable:392:12)\n    at _write (node:internal/streams/writable:333:10)\n    at Writable.write (node:internal/streams/writable:337:10)\n    at Console.log (/home/foundry/foundryvtt/resources/app/node_modules/winston/lib/winston/transports/console.js:79:23)\n    at Console._write (/home/foundry/foundryvtt/resources/app/node_modules/winston-transport/index.js:103:17)\n    at doWrite (/home/foundry/foundryvtt/resources/app/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:390:139)","syscall":"write","timestamp":"2023-08-28 17:02:17"}
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment]
A `"write EIO"` issue means that it was unable to write data to disk, either because your disk was full or otherwise unavailable for write. This is not a reproducible Foundry VTT problem and is something that will require you to do a bit of individual troubleshooting of your Linux install environment to correct. We can provide guidance via our support channels at https://foundryvtt.com/contact-us/ or on Discord at discord.gg/foundryvtt.
